[package]
name = "solina"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

num-bigint = "0.4.3"
# serde = "1.0.152"
keccak-hash = "0.10.0"
thiserror = "1.0.39"
